### ISSUE TITLE
Large frame drops if timeframe is set to a high value

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Toofifty/xp-meter#1]
I liked the idea of using this with the cumulative tracking mode and a span of 3600 seconds, however such a long time tracking data it seems to hit its limit and begins dropping your frame rate each time it updates the graph.

Any chance you can take a look and see if it can be optimized?

**Comment by Toofifty** [comment]
Hi @Jin-Jiyunsun, thanks for submitting an issue.

Do you have the "Use cache" option enabled? It should alleviate most frame drops when calculating plot points.

If that's still not performing well, can you please enable the "Show performance" option and send me a screenshot of an instance where it's causing framerate issues? Can you also let me know if you get the same issues when using a sliding window on that long of a span? 

Thanks!

**Comment by Jin-Jiyunsun** [comment]
I do not, I'll give that a try and report back if it doesnt resolve it.

**Comment by Jin-Jiyunsun** [comment]
It stopped almost all, if not all, the big stutters but still has a sinificant impact overall on my fps, down about 30 or so with caching on
![image](https://github.com/Toofifty/xp-meter/assets/37377657/2c0998be-c96b-40f1-a2f3-c6215dc6d9f5)

**Comment by Toofifty** [comment]
Thanks for that. Good to see using cache stopped the stuttering, in the next release I'll remove the config option for it.

As for the FPS drops, I've got a few ideas of how I can optimize the rendering but in the meantime you may be able to change the resolution setting to improve your FPS.

**Comment by Toofifty** [comment]
Hey so I've got some pretty big performance improvements coming in the next update (https://github.com/runelite/plugin-hub/pull/5154) which should take care of this. I'm going to close this for now, but if you still get performance issues once the update is released please open another issue. Thanks!
